#!/bin/sh

if [ -d "$HOME/.rvm/bin" ]; then
  PATH="$HOME/.rvm/bin:$PATH"
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
  
  if [ -f ".ruby-version "]; then
    rvm use "$(cat .ruby-version)"
  fi
  
  if [ -f ".ruby-gemset" ]; then
    rvm gemset use "$(cat .ruby-gemset)"
  fi
fi 
exec < /dev/tty

.git/hooks/emoji-script.rb $1
